name: Deploy to S3 with Quarto

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * 1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - uses: quarto-dev/quarto-actions/setup@v2

    - uses: r-lib/actions/setup-r@v2

    - uses: r-lib/actions/setup-pandoc@v2

    - run: |
        sudo apt-get update
        sudo apt-get -y install libicu-dev libx11-dev libpng-dev \
          libfontconfig1-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev \
          libxml2-dev libssl-dev python3 libfftw3-dev libjpeg-dev libtiff-dev \
          libcurl4-openssl-dev libgit2-dev zlib1g-dev libwebp-dev libglpk-dev

    - uses: r-lib/actions/setup-renv@v2

    - uses: quarto-dev/quarto-actions/render@v2

    - name: Setup MinIO client
      if: github.event_name != 'pull_request'
      uses: lovellfelix/minio-deploy-action@v1
      with:
        endpoint: https://s3.embl.de/
        access_key: 4kRFKz352s8UbsA6Pycq
        secret_key: ${{ secrets.MINIO_SECRET_KEY }}
        bucket: 'www-huber'
        target_dir: '/group/'
        source_dir: '_site'
